# Importando bases

In [56]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import GaussianNB
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC
from sklearn.neural_network import MLPClassifier

In [2]:
df_bolsonaro_train = pd.read_excel('Bolsonaro_treino_sem_stop.xlsx')  
df_lula_train = pd.read_excel('Lula_treino_sem_stop.xlsx') 
df_simone_train = pd.read_excel('Simone_treino_sem_stop.xlsx') 
df_ciro_train = pd.read_excel('Ciro_treino_sem_stop.xlsx') 

In [3]:
df_bolsonaro = pd.read_excel('Bolsonaro_todos_sem_stop.xlsx', index_col=0)
df_lula = pd.read_excel('Lula_todos_sem_stop.xlsx', index_col=0)
df_simone = pd.read_excel('Simone_todos_sem_stop.xlsx', index_col=0)
df_ciro = pd.read_excel('Ciro_todos_sem_stop.xlsx', index_col=0)



In [4]:
df_lula_train = df_lula_train[df_lula_train['Sentimento']!=' ']

In [5]:
# Bag Of Words

def Bag_of_words(df):
    matrix = CountVectorizer()
    text = []
    for i in df.index:
        text.append("".join(df['novo_texto'][i]))
    X = matrix.fit_transform(text)
    return X, matrix

def Bag_of_words_teste(df, matrix):
    text = []
    for i in df.index:
        text.append("".join(df['novo_texto'][i]))
    X = matrix.transform(text)
    return X

def tfidf(df):
    matrix = TfidfVectorizer()
    text = []
    for i in df.index:
        text.append("".join(df['novo_texto'][i]))
    X = matrix.fit_transform(text)
    return X, matrix

def tfidf_teste(df, matrix):
    text = []
    for i in df.index:
        text.append("".join(df['novo_texto'][i]))
    X = matrix.transform(text)
    return X



## Base treino bag of words

In [6]:
X_bw_bolsonaro_train, bw_bolsonaro = Bag_of_words(df_bolsonaro_train)
X_bw_lula_train, bw_lula = Bag_of_words(df_lula_train)
X_bw_simone_train, bw_simone = Bag_of_words(df_simone_train)
X_bw_ciro_train, bw_ciro = Bag_of_words(df_ciro_train)

## Base treino tfidf

In [7]:
X_tfidf_bolsonaro_train, tfidf_bolsonaro = tfidf(df_bolsonaro_train)
X_tfidf_lula_train, tfidf_lula = tfidf(df_lula_train)
X_tfidf_simone_train, tfidf_simone = tfidf(df_simone_train)
X_tfidf_ciro_train, tfidf_ciro = tfidf(df_ciro_train)

# Predict treino

In [8]:
Y_bolsonaro_train = df_bolsonaro_train['Sentimento'].str.replace('p','1').replace('x','0').replace('n','-1').astype(int)
Y_lula_train = df_lula_train['Sentimento'].str.replace('p','1').replace('x','0').replace('n','-1').astype(int)
Y_simone_train = df_simone_train['Sentimento'].str.replace('p','1').replace('x','0').replace('n','-1').astype(int)
Y_ciro_train = df_ciro_train['Sentimento'].str.replace('p','1').replace('x','0').replace('n','-1').astype(int)

## Bolsonaro

### Bolsonaro - Arvore de Decisao - bw

In [9]:
tree_bolsonaro_bw = tree.DecisionTreeClassifier()
tree_bolsonaro_bw = tree_bolsonaro_bw.fit(X_bw_bolsonaro_train, Y_bolsonaro_train)

i1=0
for i in range(5000,len(df_bolsonaro),5000):
    if (i==5000):
        predict_bolsonaro_bw_tree = tree_bolsonaro_bw.predict(Bag_of_words_teste(df_bolsonaro[i1:i], bw_bolsonaro).toarray())
    else:
        predict_bolsonaro_bw_tree = np.append(predict_bolsonaro_bw_tree, tree_bolsonaro_bw.predict(Bag_of_words_teste(df_bolsonaro[i1:i], bw_bolsonaro).toarray()))
    i1=i

predict_bolsonaro_bw_tree = np.append(predict_bolsonaro_bw_tree,tree_bolsonaro_bw.predict(Bag_of_words_teste(df_bolsonaro[i1:], bw_bolsonaro).toarray()))


df_bolsonaro['predict_bw_ArvoreDeDecisao'] = predict_bolsonaro_bw_tree

np.unique(predict_bolsonaro_bw_tree, return_counts=True)

(array([-1,  0,  1]), array([150453,   8193, 787792], dtype=int64))

### Bolsonaro - Arvore de Decisao - tfidf

In [10]:
tree_bolsonaro_tfidf = tree.DecisionTreeClassifier()
tree_bolsonaro_tfidf = tree_bolsonaro_tfidf.fit(X_tfidf_bolsonaro_train, Y_bolsonaro_train)

i1=0
for i in range(5000,len(df_bolsonaro),5000):
    if (i==5000):
        predict_bolsonaro_tfidf_tree = tree_bolsonaro_tfidf.predict(tfidf_teste(df_bolsonaro[i1:i], tfidf_bolsonaro).toarray())
    else:
        predict_bolsonaro_tfidf_tree = np.append(predict_bolsonaro_tfidf_tree, tree_bolsonaro_tfidf.predict(tfidf_teste(df_bolsonaro[i1:i], tfidf_bolsonaro).toarray()))
    i1=i

predict_bolsonaro_tfidf_tree = np.append(predict_bolsonaro_tfidf_tree,tree_bolsonaro_tfidf.predict(tfidf_teste(df_bolsonaro[i1:], tfidf_bolsonaro).toarray()))


df_bolsonaro['predict_tfidf_ArvoreDeDecisao'] = predict_bolsonaro_tfidf_tree

np.unique(predict_bolsonaro_tfidf_tree, return_counts=True)

(array([-1,  0,  1]), array([159695,   8465, 778278], dtype=int64))

### Bolsonaro - Naive Bayes - bw

In [12]:
GaussianNB_bolsonaro_bw = GaussianNB()
GaussianNB_bolsonaro_bw = GaussianNB_bolsonaro_bw.fit(X_bw_bolsonaro_train.toarray(), Y_bolsonaro_train)

i1=0
for i in range(5000,len(df_bolsonaro),5000):
    if (i==5000):
        predict_bolsonaro_bw_nb = GaussianNB_bolsonaro_bw.predict(Bag_of_words_teste(df_bolsonaro[i1:i], bw_bolsonaro).toarray())
    else:
        predict_bolsonaro_bw_nb = np.append(predict_bolsonaro_bw_nb, GaussianNB_bolsonaro_bw.predict(Bag_of_words_teste(df_bolsonaro[i1:i], bw_bolsonaro).toarray()))
    i1=i

predict_bolsonaro_bw_nb = np.append(predict_bolsonaro_bw_nb,GaussianNB_bolsonaro_bw.predict(Bag_of_words_teste(df_bolsonaro[i1:], bw_bolsonaro).toarray()))

df_bolsonaro['predict_bw_NaiveBayes'] = predict_bolsonaro_bw_nb

np.unique(predict_bolsonaro_bw_nb, return_counts=True)

(array([-1,  0,  1]), array([337731,  17663, 591044], dtype=int64))

### Bolsonaro - Naive Bayes - tfidf

In [13]:
GaussianNB_bolsonaro_tfidf = GaussianNB()
GaussianNB_bolsonaro_tfidf = GaussianNB_bolsonaro_tfidf.fit(X_tfidf_bolsonaro_train.toarray(), Y_bolsonaro_train)

i1=0
for i in range(5000,len(df_bolsonaro),5000):
    if (i==5000):
        predict_bolsonaro_tfidf_nb = GaussianNB_bolsonaro_tfidf.predict(tfidf_teste(df_bolsonaro[i1:i], tfidf_bolsonaro).toarray())
    else:
        predict_bolsonaro_tfidf_nb = np.append(predict_bolsonaro_tfidf_nb, GaussianNB_bolsonaro_tfidf.predict(tfidf_teste(df_bolsonaro[i1:i], tfidf_bolsonaro).toarray()))
    i1=i

predict_bolsonaro_tfidf_nb = np.append(predict_bolsonaro_tfidf_nb,GaussianNB_bolsonaro_tfidf.predict(tfidf_teste(df_bolsonaro[i1:], tfidf_bolsonaro).toarray()))

df_bolsonaro['predict_tfidf_NaiveBayes'] = predict_bolsonaro_tfidf_nb

np.unique(predict_bolsonaro_tfidf_nb, return_counts=True)

(array([-1,  0,  1]), array([336837,  17812, 591789], dtype=int64))

### Bolsonaro - Random Forest - bw

In [31]:
RandomForest_bolsonaro_bw = RandomForestClassifier()
RandomForest_bolsonaro_bw = RandomForest_bolsonaro_bw.fit(X_bw_bolsonaro_train.toarray(), Y_bolsonaro_train)

i1=0
for i in range(5000,len(df_bolsonaro),5000):
    if (i==5000):
        predict_bolsonaro_bw_rf = RandomForest_bolsonaro_bw.predict(Bag_of_words_teste(df_bolsonaro[i1:i], bw_bolsonaro).toarray())
    else:
        predict_bolsonaro_bw_rf = np.append(predict_bolsonaro_bw_rf, RandomForest_bolsonaro_bw.predict(Bag_of_words_teste(df_bolsonaro[i1:i], bw_bolsonaro).toarray()))
    i1=i

predict_bolsonaro_bw_rf = np.append(predict_bolsonaro_bw_rf,RandomForest_bolsonaro_bw.predict(Bag_of_words_teste(df_bolsonaro[i1:], bw_bolsonaro).toarray()))

df_bolsonaro['predict_bw_RandomForest'] = predict_bolsonaro_bw_rf

np.unique(predict_bolsonaro_bw_rf, return_counts=True)

(array([-1,  0,  1]), array([ 35177,   2794, 908467], dtype=int64))

### Bolsonaro - Random Forest - tfidf

In [33]:
RandomForest_bolsonaro_tfidf = RandomForestClassifier()
RandomForest_bolsonaro_tfidf = RandomForest_bolsonaro_tfidf.fit(X_tfidf_bolsonaro_train.toarray(), Y_bolsonaro_train)

i1=0
for i in range(5000,len(df_bolsonaro),5000):
    if (i==5000):
        predict_bolsonaro_tfidf_rf = RandomForest_bolsonaro_tfidf.predict(tfidf_teste(df_bolsonaro[i1:i], tfidf_bolsonaro).toarray())
    else:
        predict_bolsonaro_tfidf_rf = np.append(predict_bolsonaro_tfidf_rf, RandomForest_bolsonaro_tfidf.predict(tfidf_teste(df_bolsonaro[i1:i], tfidf_bolsonaro).toarray()))
    i1=i

predict_bolsonaro_tfidf_rf = np.append(predict_bolsonaro_tfidf_rf,RandomForest_bolsonaro_tfidf.predict(tfidf_teste(df_bolsonaro[i1:], tfidf_bolsonaro).toarray()))

df_bolsonaro['predict_tfidf_RandomForest'] = predict_bolsonaro_tfidf_rf

np.unique(predict_bolsonaro_tfidf_rf, return_counts=True)

(array([-1,  0,  1]), array([ 17225,   3903, 925310], dtype=int64))

### Bolsonaro - SVM - bw

In [47]:
svc_bolsonaro_bw = LinearSVC()
svc_bolsonaro_bw = svc_bolsonaro_bw.fit(X_bw_bolsonaro_train.toarray(), Y_bolsonaro_train)

i1=0
for i in range(5000,len(df_bolsonaro),5000):
    if (i==5000):
        predict_bolsonaro_bw_svc = svc_bolsonaro_bw.predict(Bag_of_words_teste(df_bolsonaro[i1:i], bw_bolsonaro).toarray())
    else:
        predict_bolsonaro_bw_svc = np.append(predict_bolsonaro_bw_svc, svc_bolsonaro_bw.predict(Bag_of_words_teste(df_bolsonaro[i1:i], bw_bolsonaro).toarray()))
    i1=i

predict_bolsonaro_bw_svc = np.append(predict_bolsonaro_bw_svc,svc_bolsonaro_bw.predict(Bag_of_words_teste(df_bolsonaro[i1:], bw_bolsonaro).toarray()))

df_bolsonaro['predict_bw_svc'] = predict_bolsonaro_bw_svc

np.unique(predict_bolsonaro_bw_svc, return_counts=True)

(array([-1,  0,  1]), array([130759,   4211, 811468], dtype=int64))

### Bolsonaro - SVM - tfidf

In [48]:
svc_bolsonaro_tfidf = LinearSVC()
svc_bolsonaro_tfidf = svc_bolsonaro_tfidf.fit(X_tfidf_bolsonaro_train.toarray(), Y_bolsonaro_train)

i1=0
for i in range(5000,len(df_bolsonaro),5000):
    if (i==5000):
        predict_bolsonaro_tfidf_svc = svc_bolsonaro_tfidf.predict(tfidf_teste(df_bolsonaro[i1:i], tfidf_bolsonaro).toarray())
    else:
        predict_bolsonaro_tfidf_svc = np.append(predict_bolsonaro_tfidf_svc, svc_bolsonaro_tfidf.predict(tfidf_teste(df_bolsonaro[i1:i], tfidf_bolsonaro).toarray()))
    i1=i

predict_bolsonaro_tfidf_svc = np.append(predict_bolsonaro_tfidf_svc,svc_bolsonaro_tfidf.predict(tfidf_teste(df_bolsonaro[i1:], tfidf_bolsonaro).toarray()))

df_bolsonaro['predict_tfidf_svc'] = predict_bolsonaro_tfidf_svc

np.unique(predict_bolsonaro_tfidf_svc, return_counts=True)

(array([-1,  0,  1]), array([ 47202,     92, 899144], dtype=int64))

### Bolsonaro - MLP - bw

In [57]:
mlp_bolsonaro_bw = MLPClassifier()
mlp_bolsonaro_bw = mlp_bolsonaro_bw.fit(X_bw_bolsonaro_train.toarray(), Y_bolsonaro_train)

i1=0
for i in range(5000,len(df_bolsonaro),5000):
    if (i==5000):
        predict_bolsonaro_bw_mlp = mlp_bolsonaro_bw.predict(Bag_of_words_teste(df_bolsonaro[i1:i], bw_bolsonaro).toarray())
    else:
        predict_bolsonaro_bw_mlp = np.append(predict_bolsonaro_bw_mlp, mlp_bolsonaro_bw.predict(Bag_of_words_teste(df_bolsonaro[i1:i], bw_bolsonaro).toarray()))
    i1=i

predict_bolsonaro_bw_mlp = np.append(predict_bolsonaro_bw_mlp,mlp_bolsonaro_bw.predict(Bag_of_words_teste(df_bolsonaro[i1:], bw_bolsonaro).toarray()))

df_bolsonaro['predict_bw_mlp'] = predict_bolsonaro_bw_mlp
df_bolsonaro['predict_bw_mlp2'] = predict_bolsonaro_bw_mlp

np.unique(predict_bolsonaro_bw_mlp, return_counts=True)

Iteration 1, loss = 0.77253503
Iteration 2, loss = 0.48574396
Iteration 3, loss = 0.37868152
Iteration 4, loss = 0.29864111
Iteration 5, loss = 0.23645597
Iteration 6, loss = 0.18909241
Iteration 7, loss = 0.15265182
Iteration 8, loss = 0.12468498
Iteration 9, loss = 0.10215033
Iteration 10, loss = 0.08444633
Iteration 11, loss = 0.07039765
Iteration 12, loss = 0.05895100
Iteration 13, loss = 0.05012049
Iteration 14, loss = 0.04277194
Iteration 15, loss = 0.03699673
Iteration 16, loss = 0.03191597
Iteration 17, loss = 0.02803580
Iteration 18, loss = 0.02483467
Iteration 19, loss = 0.02206917
Iteration 20, loss = 0.01996539
Iteration 21, loss = 0.01784546
Iteration 22, loss = 0.01619280
Iteration 23, loss = 0.01487629
Iteration 24, loss = 0.01367443
Iteration 25, loss = 0.01269454
Iteration 26, loss = 0.01175903
Iteration 27, loss = 0.01090482
Iteration 28, loss = 0.01012915
Iteration 29, loss = 0.00952184
Iteration 30, loss = 0.00911158
Iteration 31, loss = 0.00861956
Iteration 32, los

(array([-1,  0,  1]), array([158527,   4806, 783105], dtype=int64))

### Bolsonaro - MLP - tfidf

In [60]:
mlp_bolsonaro_tfidf = MLPClassifier()
mlp_bolsonaro_tfidf = mlp_bolsonaro_tfidf.fit(X_tfidf_bolsonaro_train.toarray(), Y_bolsonaro_train)

i1=0
for i in range(5000,len(df_bolsonaro),5000):
    if (i==5000):
        predict_bolsonaro_tfidf_mlp = mlp_bolsonaro_tfidf.predict(tfidf_teste(df_bolsonaro[i1:i], tfidf_bolsonaro).toarray())
    else:
        predict_bolsonaro_tfidf_mlp = np.append(predict_bolsonaro_tfidf_mlp, mlp_bolsonaro_tfidf.predict(tfidf_teste(df_bolsonaro[i1:i], tfidf_bolsonaro).toarray()))
    i1=i

predict_bolsonaro_tfidf_mlp = np.append(predict_bolsonaro_tfidf_mlp,mlp_bolsonaro_tfidf.predict(tfidf_teste(df_bolsonaro[i1:], tfidf_bolsonaro).toarray()))

df_bolsonaro['predict_tfidf_mlp'] = predict_bolsonaro_tfidf_mlp
df_bolsonaro['predict_tfidf_mlp2'] = predict_bolsonaro_tfidf_mlp

np.unique(predict_bolsonaro_tfidf_mlp, return_counts=True)

(array([-1,  0,  1]), array([152195,   3494, 790749], dtype=int64))

# Lula

### Lula - Arvore de Decisao - bw

In [14]:
tree_lula_bw = tree.DecisionTreeClassifier()
tree_lula_bw = tree_lula_bw.fit(X_bw_lula_train, Y_lula_train)

i1=0
for i in range(5000,len(df_lula),5000):
    if (i==5000):
        predict_lula_bw_tree = tree_lula_bw.predict(Bag_of_words_teste(df_lula[i1:i], bw_lula).toarray())
    else:
        predict_lula_bw_tree = np.append(predict_lula_bw_tree, tree_lula_bw.predict(Bag_of_words_teste(df_lula[i1:i], bw_lula).toarray()))
    i1=i

predict_lula_bw_tree = np.append(predict_lula_bw_tree,tree_lula_bw.predict(Bag_of_words_teste(df_lula[i1:], bw_lula).toarray()))


df_lula['predict_bw_ArvoreDeDecisao'] = predict_lula_bw_tree

np.unique(predict_lula_bw_tree, return_counts=True)

(array([-1,  0,  1]), array([ 86569,   1381, 843780], dtype=int64))

### Lula - Arvore de Decisao - tfidf

In [15]:
tree_lula_tfidf = tree.DecisionTreeClassifier()
tree_lula_tfidf = tree_lula_tfidf.fit(X_tfidf_lula_train, Y_lula_train)

i1=0
for i in range(5000,len(df_lula),5000):
    if (i==5000):
        predict_lula_tfidf_tree = tree_lula_tfidf.predict(tfidf_teste(df_lula[i1:i], tfidf_lula).toarray())
    else:
        predict_lula_tfidf_tree = np.append(predict_lula_tfidf_tree, tree_lula_tfidf.predict(tfidf_teste(df_lula[i1:i], tfidf_lula).toarray()))
    i1=i

predict_lula_tfidf_tree = np.append(predict_lula_tfidf_tree,tree_lula_tfidf.predict(tfidf_teste(df_lula[i1:], tfidf_lula).toarray()))


df_lula['predict_tfidf_ArvoreDeDecisao'] = predict_lula_tfidf_tree

np.unique(predict_lula_tfidf_tree, return_counts=True)

(array([-1,  0,  1]), array([146493,    989, 784248], dtype=int64))

### Lula - Naive Bayes - bw

In [16]:
GaussianNB_lula_bw = GaussianNB()
GaussianNB_lula_bw = GaussianNB_lula_bw.fit(X_bw_lula_train.toarray(), Y_lula_train)

i1=0
for i in range(5000,len(df_lula),5000):
    if (i==5000):
        predict_lula_bw_nb = GaussianNB_lula_bw.predict(Bag_of_words_teste(df_lula[i1:i], bw_lula).toarray())
    else:
        predict_lula_bw_nb = np.append(predict_lula_bw_nb, GaussianNB_lula_bw.predict(Bag_of_words_teste(df_lula[i1:i], bw_lula).toarray()))
    i1=i

predict_lula_bw_nb = np.append(predict_lula_bw_nb,GaussianNB_lula_bw.predict(Bag_of_words_teste(df_lula[i1:], bw_lula).toarray()))

df_lula['predict_bw_NaiveBayes'] = predict_lula_bw_nb

np.unique(predict_lula_bw_nb, return_counts=True)

(array([-1,  0,  1]), array([404172,   7081, 520477], dtype=int64))

### Lula - Naive Bayes - tfidf

In [17]:
GaussianNB_lula_tfidf = GaussianNB()
GaussianNB_lula_tfidf = GaussianNB_lula_tfidf.fit(X_tfidf_lula_train.toarray(), Y_lula_train)

i1=0
for i in range(5000,len(df_lula),5000):
    if (i==5000):
        predict_lula_tfidf_nb = GaussianNB_lula_tfidf.predict(tfidf_teste(df_lula[i1:i], tfidf_lula).toarray())
    else:
        predict_lula_tfidf_nb = np.append(predict_lula_tfidf_nb, GaussianNB_lula_tfidf.predict(tfidf_teste(df_lula[i1:i], tfidf_lula).toarray()))
    i1=i

predict_lula_tfidf_nb = np.append(predict_lula_tfidf_nb,GaussianNB_lula_tfidf.predict(tfidf_teste(df_lula[i1:], tfidf_lula).toarray()))

df_lula['predict_tfidf_NaiveBayes'] = predict_lula_tfidf_nb

np.unique(predict_lula_tfidf_nb, return_counts=True)

(array([-1,  0,  1]), array([402035,   7089, 522606], dtype=int64))

### Lula - Random Forest - bw

In [35]:
RandomForest_lula_bw = RandomForestClassifier()
RandomForest_lula_bw = RandomForest_lula_bw.fit(X_bw_lula_train.toarray(), Y_lula_train)

i1=0
for i in range(5000,len(df_lula),5000):
    if (i==5000):
        predict_lula_bw_rf = RandomForest_lula_bw.predict(Bag_of_words_teste(df_lula[i1:i], bw_lula).toarray())
    else:
        predict_lula_bw_rf = np.append(predict_lula_bw_rf, RandomForest_lula_bw.predict(Bag_of_words_teste(df_lula[i1:i], bw_lula).toarray()))
    i1=i

predict_lula_bw_rf = np.append(predict_lula_bw_rf,RandomForest_lula_bw.predict(Bag_of_words_teste(df_lula[i1:], bw_lula).toarray()))

df_lula['predict_bw_RandomForest'] = predict_lula_bw_rf

np.unique(predict_lula_bw_rf, return_counts=True)

(array([-1,  0,  1]), array([ 20454,     30, 911246], dtype=int64))

### Lula - Random Forest - tfidf

In [36]:
RandomForest_lula_tfidf = RandomForestClassifier()
RandomForest_lula_tfidf = RandomForest_lula_tfidf.fit(X_tfidf_lula_train.toarray(), Y_lula_train)

i1=0
for i in range(5000,len(df_lula),5000):
    if (i==5000):
        predict_lula_tfidf_rf = RandomForest_lula_tfidf.predict(tfidf_teste(df_lula[i1:i], tfidf_lula).toarray())
    else:
        predict_lula_tfidf_rf = np.append(predict_lula_tfidf_rf, RandomForest_lula_tfidf.predict(tfidf_teste(df_lula[i1:i], tfidf_lula).toarray()))
    i1=i

predict_lula_tfidf_rf = np.append(predict_lula_tfidf_rf,RandomForest_lula_tfidf.predict(tfidf_teste(df_lula[i1:], tfidf_lula).toarray()))

df_lula['predict_tfidf_RandomForest'] = predict_lula_tfidf_rf

np.unique(predict_lula_tfidf_rf, return_counts=True)

(array([-1,  0,  1]), array([ 18367,     28, 913335], dtype=int64))

### lula - SVM - bw

In [50]:
svc_lula_bw = LinearSVC()
svc_lula_bw = svc_lula_bw.fit(X_bw_lula_train.toarray(), Y_lula_train)

i1=0
for i in range(5000,len(df_lula),5000):
    if (i==5000):
        predict_lula_bw_svc = svc_lula_bw.predict(Bag_of_words_teste(df_lula[i1:i], bw_lula).toarray())
    else:
        predict_lula_bw_svc = np.append(predict_lula_bw_svc, svc_lula_bw.predict(Bag_of_words_teste(df_lula[i1:i], bw_lula).toarray()))
    i1=i

predict_lula_bw_svc = np.append(predict_lula_bw_svc,svc_lula_bw.predict(Bag_of_words_teste(df_lula[i1:], bw_lula).toarray()))

df_lula['predict_bw_svc'] = predict_lula_bw_svc

np.unique(predict_lula_bw_svc, return_counts=True)

C:\Users\daian\anaconda3\lib\site-packages\sklearn\svm\_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


(array([-1,  0,  1]), array([118844,    170, 812716], dtype=int64))

### lula - SVM - tfidf

In [51]:
svc_lula_tfidf = LinearSVC()
svc_lula_tfidf = svc_lula_tfidf.fit(X_tfidf_lula_train.toarray(), Y_lula_train)

i1=0
for i in range(5000,len(df_lula),5000):
    if (i==5000):
        predict_lula_tfidf_svc = svc_lula_tfidf.predict(tfidf_teste(df_lula[i1:i], tfidf_lula).toarray())
    else:
        predict_lula_tfidf_svc = np.append(predict_lula_tfidf_svc, svc_lula_tfidf.predict(tfidf_teste(df_lula[i1:i], tfidf_lula).toarray()))
    i1=i

predict_lula_tfidf_svc = np.append(predict_lula_tfidf_svc,svc_lula_tfidf.predict(tfidf_teste(df_lula[i1:], tfidf_lula).toarray()))

df_lula['predict_tfidf_svc'] = predict_lula_tfidf_svc

np.unique(predict_lula_tfidf_svc, return_counts=True)

(array([-1,  0,  1]), array([ 49478,     20, 882232], dtype=int64))

### Lula - MLP - bw

In [61]:
mlp_lula_bw = MLPClassifier()
mlp_lula_bw = mlp_lula_bw.fit(X_bw_lula_train.toarray(), Y_lula_train)

i1=0
for i in range(5000,len(df_lula),5000):
    if (i==5000):
        predict_lula_bw_mlp = mlp_lula_bw.predict(Bag_of_words_teste(df_lula[i1:i], bw_lula).toarray())
    else:
        predict_lula_bw_mlp = np.append(predict_lula_bw_mlp, mlp_lula_bw.predict(Bag_of_words_teste(df_lula[i1:i], bw_lula).toarray()))
    i1=i

predict_lula_bw_mlp = np.append(predict_lula_bw_mlp,mlp_lula_bw.predict(Bag_of_words_teste(df_lula[i1:], bw_lula).toarray()))

df_lula['predict_bw_mlp'] = predict_lula_bw_mlp
df_lula['predict_bw_mlp2'] = predict_lula_bw_mlp

np.unique(predict_lula_bw_mlp, return_counts=True)

(array([-1,  0,  1]), array([120073,    484, 811173], dtype=int64))

### Lula - MLP - tfidf

In [64]:
mlp_lula_tfidf = MLPClassifier()
mlp_lula_tfidf = mlp_lula_tfidf.fit(X_tfidf_lula_train.toarray(), Y_lula_train)

i1=0
for i in range(5000,len(df_lula),5000):
    if (i==5000):
        predict_lula_tfidf_mlp = mlp_lula_tfidf.predict(tfidf_teste(df_lula[i1:i], tfidf_lula).toarray())
    else:
        predict_lula_tfidf_mlp = np.append(predict_lula_tfidf_mlp, mlp_lula_tfidf.predict(tfidf_teste(df_lula[i1:i], tfidf_lula).toarray()))
    i1=i

predict_lula_tfidf_mlp = np.append(predict_lula_tfidf_mlp,mlp_lula_tfidf.predict(tfidf_teste(df_lula[i1:], tfidf_lula).toarray()))

df_lula['predict_tfidf_mlp'] = predict_lula_tfidf_mlp
df_lula['predict_tfidf_mlp2'] = predict_lula_tfidf_mlp

np.unique(predict_lula_tfidf_mlp, return_counts=True)

(array([-1,  0,  1]), array([124659,     97, 806974], dtype=int64))

# Simone

### Simone - Arvore de Decisao - bw

In [18]:
tree_simone_bw = tree.DecisionTreeClassifier()
tree_simone_bw = tree_simone_bw.fit(X_bw_simone_train, Y_simone_train)

i1=0
for i in range(5000,len(df_simone),5000):
    if (i==5000):
        predict_simone_bw_tree = tree_simone_bw.predict(Bag_of_words_teste(df_simone[i1:i], bw_simone).toarray())
    else:
        predict_simone_bw_tree = np.append(predict_simone_bw_tree, tree_simone_bw.predict(Bag_of_words_teste(df_simone[i1:i], bw_simone).toarray()))
    i1=i

predict_simone_bw_tree = np.append(predict_simone_bw_tree,tree_simone_bw.predict(Bag_of_words_teste(df_simone[i1:], bw_simone).toarray()))


df_simone['predict_bw_ArvoreDeDecisao'] = predict_simone_bw_tree

np.unique(predict_simone_bw_tree, return_counts=True)

(array([-1,  0,  1]), array([12480, 71987, 46695], dtype=int64))

### Simone - Arvore de Decisao - tfidf

In [19]:
tree_simone_tfidf = tree.DecisionTreeClassifier()
tree_simone_tfidf = tree_simone_tfidf.fit(X_tfidf_simone_train, Y_simone_train)

i1=0
for i in range(5000,len(df_simone),5000):
    if (i==5000):
        predict_simone_tfidf_tree = tree_simone_tfidf.predict(tfidf_teste(df_simone[i1:i], tfidf_simone).toarray())
    else:
        predict_simone_tfidf_tree = np.append(predict_simone_tfidf_tree, tree_simone_tfidf.predict(tfidf_teste(df_simone[i1:i], tfidf_simone).toarray()))
    i1=i

predict_simone_tfidf_tree = np.append(predict_simone_tfidf_tree,tree_simone_tfidf.predict(tfidf_teste(df_simone[i1:], tfidf_simone).toarray()))


df_simone['predict_tfidf_ArvoreDeDecisao'] = predict_simone_tfidf_tree

np.unique(predict_simone_tfidf_tree, return_counts=True)

(array([-1,  0,  1]), array([ 8107, 73678, 49377], dtype=int64))

### Simone - Naive Bayes - bw

In [20]:
GaussianNB_simone_bw = GaussianNB()
GaussianNB_simone_bw = GaussianNB_simone_bw.fit(X_bw_simone_train.toarray(), Y_simone_train)

i1=0
for i in range(5000,len(df_simone),5000):
    if (i==5000):
        predict_simone_bw_nb = GaussianNB_simone_bw.predict(Bag_of_words_teste(df_simone[i1:i], bw_simone).toarray())
    else:
        predict_simone_bw_nb = np.append(predict_simone_bw_nb, GaussianNB_simone_bw.predict(Bag_of_words_teste(df_simone[i1:i], bw_simone).toarray()))
    i1=i

predict_simone_bw_nb = np.append(predict_simone_bw_nb,GaussianNB_simone_bw.predict(Bag_of_words_teste(df_simone[i1:], bw_simone).toarray()))

df_simone['predict_bw_NaiveBayes'] = predict_simone_bw_nb

np.unique(predict_simone_bw_nb, return_counts=True)

(array([-1,  0,  1]), array([13226, 67265, 50671], dtype=int64))

### Simone - Naive Bayes - tfidf

In [21]:
GaussianNB_simone_tfidf = GaussianNB()
GaussianNB_simone_tfidf = GaussianNB_simone_tfidf.fit(X_tfidf_simone_train.toarray(), Y_simone_train)

i1=0
for i in range(5000,len(df_simone),5000):
    if (i==5000):
        predict_simone_tfidf_nb = GaussianNB_simone_tfidf.predict(tfidf_teste(df_simone[i1:i], tfidf_simone).toarray())
    else:
        predict_simone_tfidf_nb = np.append(predict_simone_tfidf_nb, GaussianNB_simone_tfidf.predict(tfidf_teste(df_simone[i1:i], tfidf_simone).toarray()))
    i1=i

predict_simone_tfidf_nb = np.append(predict_simone_tfidf_nb,GaussianNB_simone_tfidf.predict(tfidf_teste(df_simone[i1:], tfidf_simone).toarray()))

df_simone['predict_tfidf_NaiveBayes'] = predict_simone_tfidf_nb

np.unique(predict_simone_tfidf_nb, return_counts=True)

(array([-1,  0,  1]), array([12320, 61231, 57611], dtype=int64))

### Simone - Random Forest - bw

In [37]:
RandomForest_simone_bw = RandomForestClassifier()
RandomForest_simone_bw = RandomForest_simone_bw.fit(X_bw_simone_train.toarray(), Y_simone_train)

i1=0
for i in range(5000,len(df_simone),5000):
    if (i==5000):
        predict_simone_bw_rf = RandomForest_simone_bw.predict(Bag_of_words_teste(df_simone[i1:i], bw_simone).toarray())
    else:
        predict_simone_bw_rf = np.append(predict_simone_bw_rf, RandomForest_simone_bw.predict(Bag_of_words_teste(df_simone[i1:i], bw_simone).toarray()))
    i1=i

predict_simone_bw_rf = np.append(predict_simone_bw_rf,RandomForest_simone_bw.predict(Bag_of_words_teste(df_simone[i1:], bw_simone).toarray()))

df_simone['predict_bw_RandomForest'] = predict_simone_bw_rf

np.unique(predict_simone_bw_rf, return_counts=True)

(array([-1,  0,  1]), array([  476, 68474, 62212], dtype=int64))

### Simone - Random Forest - tfidf

In [38]:
RandomForest_simone_tfidf = RandomForestClassifier()
RandomForest_simone_tfidf = RandomForest_simone_tfidf.fit(X_tfidf_simone_train.toarray(), Y_simone_train)

i1=0
for i in range(5000,len(df_simone),5000):
    if (i==5000):
        predict_simone_tfidf_rf = RandomForest_simone_tfidf.predict(tfidf_teste(df_simone[i1:i], tfidf_simone).toarray())
    else:
        predict_simone_tfidf_rf = np.append(predict_simone_tfidf_rf, RandomForest_simone_tfidf.predict(tfidf_teste(df_simone[i1:i], tfidf_simone).toarray()))
    i1=i

predict_simone_tfidf_rf = np.append(predict_simone_tfidf_rf,RandomForest_simone_tfidf.predict(tfidf_teste(df_simone[i1:], tfidf_simone).toarray()))

df_simone['predict_tfidf_RandomForest'] = predict_simone_tfidf_rf

np.unique(predict_simone_tfidf_rf, return_counts=True)

(array([-1,  0,  1]), array([  111, 50220, 80831], dtype=int64))

### Simone - SVM - bw

In [52]:
svc_simone_bw = LinearSVC()
svc_simone_bw = svc_simone_bw.fit(X_bw_simone_train.toarray(), Y_simone_train)

i1=0
for i in range(5000,len(df_simone),5000):
    if (i==5000):
        predict_simone_bw_svc = svc_simone_bw.predict(Bag_of_words_teste(df_simone[i1:i], bw_simone).toarray())
    else:
        predict_simone_bw_svc = np.append(predict_simone_bw_svc, svc_simone_bw.predict(Bag_of_words_teste(df_simone[i1:i], bw_simone).toarray()))
    i1=i

predict_simone_bw_svc = np.append(predict_simone_bw_svc,svc_simone_bw.predict(Bag_of_words_teste(df_simone[i1:], bw_simone).toarray()))

df_simone['predict_bw_svc'] = predict_simone_bw_svc

np.unique(predict_simone_bw_svc, return_counts=True)

(array([-1,  0,  1]), array([ 6689, 61338, 63135], dtype=int64))

### Simone - SVM - tfidf

In [53]:
svc_simone_tfidf = LinearSVC()
svc_simone_tfidf = svc_simone_tfidf.fit(X_tfidf_simone_train.toarray(), Y_simone_train)

i1=0
for i in range(5000,len(df_simone),5000):
    if (i==5000):
        predict_simone_tfidf_svc = svc_simone_tfidf.predict(tfidf_teste(df_simone[i1:i], tfidf_simone).toarray())
    else:
        predict_simone_tfidf_svc = np.append(predict_simone_tfidf_svc, svc_simone_tfidf.predict(tfidf_teste(df_simone[i1:i], tfidf_simone).toarray()))
    i1=i

predict_simone_tfidf_svc = np.append(predict_simone_tfidf_svc,svc_simone_tfidf.predict(tfidf_teste(df_simone[i1:], tfidf_simone).toarray()))

df_simone['predict_tfidf_svc'] = predict_simone_tfidf_svc

np.unique(predict_simone_tfidf_svc, return_counts=True)

(array([-1,  0,  1]), array([ 5076, 67126, 58960], dtype=int64))

### Simone - MLP - bw

In [62]:
mlp_simone_bw = MLPClassifier()
mlp_simone_bw = mlp_simone_bw.fit(X_bw_simone_train.toarray(), Y_simone_train)

i1=0
for i in range(5000,len(df_simone),5000):
    if (i==5000):
        predict_simone_bw_mlp = mlp_simone_bw.predict(Bag_of_words_teste(df_simone[i1:i], bw_simone).toarray())
    else:
        predict_simone_bw_mlp = np.append(predict_simone_bw_mlp, mlp_simone_bw.predict(Bag_of_words_teste(df_simone[i1:i], bw_simone).toarray()))
    i1=i

predict_simone_bw_mlp = np.append(predict_simone_bw_mlp,mlp_simone_bw.predict(Bag_of_words_teste(df_simone[i1:], bw_simone).toarray()))

df_simone['predict_bw_mlp'] = predict_simone_bw_mlp
df_simone['predict_bw_mlp2'] = predict_simone_bw_mlp

np.unique(predict_simone_bw_mlp, return_counts=True)

C:\Users\daian\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


(array([-1,  0,  1]), array([ 6529, 71272, 53361], dtype=int64))

### Simone - MLP - tfidf

In [65]:
mlp_simone_tfidf = MLPClassifier()
mlp_simone_tfidf = mlp_simone_tfidf.fit(X_tfidf_simone_train.toarray(), Y_simone_train)

i1=0
for i in range(5000,len(df_simone),5000):
    if (i==5000):
        predict_simone_tfidf_mlp = mlp_simone_tfidf.predict(tfidf_teste(df_simone[i1:i], tfidf_simone).toarray())
    else:
        predict_simone_tfidf_mlp = np.append(predict_simone_tfidf_mlp, mlp_simone_tfidf.predict(tfidf_teste(df_simone[i1:i], tfidf_simone).toarray()))
    i1=i

predict_simone_tfidf_mlp = np.append(predict_simone_tfidf_mlp,mlp_simone_tfidf.predict(tfidf_teste(df_simone[i1:], tfidf_simone).toarray()))

df_simone['predict_tfidf_mlp'] = predict_simone_tfidf_mlp
df_simone['predict_tfidf_mlp2'] = predict_simone_tfidf_mlp

np.unique(predict_simone_tfidf_mlp, return_counts=True)

C:\Users\daian\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


(array([-1,  0,  1]), array([ 8414, 66464, 56284], dtype=int64))

# Ciro

### Ciro - Arvore de Decisao - bw

In [22]:
tree_ciro_bw = tree.DecisionTreeClassifier()
tree_ciro_bw = tree_ciro_bw.fit(X_bw_ciro_train, Y_ciro_train)

i1=0
for i in range(5000,len(df_ciro),5000):
    if (i==5000):
        predict_ciro_bw_tree = tree_ciro_bw.predict(Bag_of_words_teste(df_ciro[i1:i], bw_ciro).toarray())
    else:
        predict_ciro_bw_tree = np.append(predict_ciro_bw_tree, tree_ciro_bw.predict(Bag_of_words_teste(df_ciro[i1:i], bw_ciro).toarray()))
    i1=i

predict_ciro_bw_tree = np.append(predict_ciro_bw_tree,tree_ciro_bw.predict(Bag_of_words_teste(df_ciro[i1:], bw_ciro).toarray()))


df_ciro['predict_bw_ArvoreDeDecisao'] = predict_ciro_bw_tree

np.unique(predict_ciro_bw_tree, return_counts=True)

(array([-1,  0,  1]), array([   767,    179, 497120], dtype=int64))

### Ciro - Arvore de Decisao - tfidf

In [23]:
tree_ciro_tfidf = tree.DecisionTreeClassifier()
tree_ciro_tfidf = tree_ciro_tfidf.fit(X_tfidf_ciro_train, Y_ciro_train)

i1=0
for i in range(5000,len(df_ciro),5000):
    if (i==5000):
        predict_ciro_tfidf_tree = tree_ciro_tfidf.predict(tfidf_teste(df_ciro[i1:i], tfidf_ciro).toarray())
    else:
        predict_ciro_tfidf_tree = np.append(predict_ciro_tfidf_tree, tree_ciro_tfidf.predict(tfidf_teste(df_ciro[i1:i], tfidf_ciro).toarray()))
    i1=i

predict_ciro_tfidf_tree = np.append(predict_ciro_tfidf_tree,tree_ciro_tfidf.predict(tfidf_teste(df_ciro[i1:], tfidf_ciro).toarray()))


df_ciro['predict_tfidf_ArvoreDeDecisao'] = predict_ciro_tfidf_tree

np.unique(predict_ciro_tfidf_tree, return_counts=True)

(array([-1,  0,  1]), array([   918,    558, 496590], dtype=int64))

### Ciro - Naive Bayes - bw

In [24]:
GaussianNB_ciro_bw = GaussianNB()
GaussianNB_ciro_bw = GaussianNB_ciro_bw.fit(X_bw_ciro_train.toarray(), Y_ciro_train)

i1=0
for i in range(5000,len(df_ciro),5000):
    if (i==5000):
        predict_ciro_bw_nb = GaussianNB_ciro_bw.predict(Bag_of_words_teste(df_ciro[i1:i], bw_ciro).toarray())
    else:
        predict_ciro_bw_nb = np.append(predict_ciro_bw_nb, GaussianNB_ciro_bw.predict(Bag_of_words_teste(df_ciro[i1:i], bw_ciro).toarray()))
    i1=i

predict_ciro_bw_nb = np.append(predict_ciro_bw_nb,GaussianNB_ciro_bw.predict(Bag_of_words_teste(df_ciro[i1:], bw_ciro).toarray()))

df_ciro['predict_bw_NaiveBayes'] = predict_ciro_bw_nb

np.unique(predict_ciro_bw_nb, return_counts=True)

(array([-1,  0,  1]), array([  5082,   3206, 489778], dtype=int64))

### Ciro - Naive Bayes - tfidf

In [25]:
GaussianNB_ciro_tfidf = GaussianNB()
GaussianNB_ciro_tfidf = GaussianNB_ciro_tfidf.fit(X_tfidf_ciro_train.toarray(), Y_ciro_train)

i1=0
for i in range(5000,len(df_ciro),5000):
    if (i==5000):
        predict_ciro_tfidf_nb = GaussianNB_ciro_tfidf.predict(tfidf_teste(df_ciro[i1:i], tfidf_ciro).toarray())
    else:
        predict_ciro_tfidf_nb = np.append(predict_ciro_tfidf_nb, GaussianNB_ciro_tfidf.predict(tfidf_teste(df_ciro[i1:i], tfidf_ciro).toarray()))
    i1=i

predict_ciro_tfidf_nb = np.append(predict_ciro_tfidf_nb,GaussianNB_ciro_tfidf.predict(tfidf_teste(df_ciro[i1:], tfidf_ciro).toarray()))

df_ciro['predict_tfidf_NaiveBayes'] = predict_ciro_tfidf_nb

np.unique(predict_ciro_tfidf_nb, return_counts=True)

(array([-1,  0,  1]), array([  5083,   3211, 489772], dtype=int64))

### Ciro - Random Forest - bw

In [39]:
RandomForest_ciro_bw = RandomForestClassifier()
RandomForest_ciro_bw = RandomForest_ciro_bw.fit(X_bw_ciro_train.toarray(), Y_ciro_train)

i1=0
for i in range(5000,len(df_ciro),5000):
    if (i==5000):
        predict_ciro_bw_rf = RandomForest_ciro_bw.predict(Bag_of_words_teste(df_ciro[i1:i], bw_ciro).toarray())
    else:
        predict_ciro_bw_rf = np.append(predict_ciro_bw_rf, RandomForest_ciro_bw.predict(Bag_of_words_teste(df_ciro[i1:i], bw_ciro).toarray()))
    i1=i

predict_ciro_bw_rf = np.append(predict_ciro_bw_rf,RandomForest_ciro_bw.predict(Bag_of_words_teste(df_ciro[i1:], bw_ciro).toarray()))

df_ciro['predict_bw_RandomForest'] = predict_ciro_bw_rf

np.unique(predict_ciro_bw_rf, return_counts=True)

(array([-1,  0,  1]), array([    12,     12, 498042], dtype=int64))

### Ciro - Random Forest - tfidf

In [40]:
RandomForest_ciro_tfidf = RandomForestClassifier()
RandomForest_ciro_tfidf = RandomForest_ciro_tfidf.fit(X_tfidf_ciro_train.toarray(), Y_ciro_train)

i1=0
for i in range(5000,len(df_ciro),5000):
    if (i==5000):
        predict_ciro_tfidf_rf = RandomForest_ciro_tfidf.predict(tfidf_teste(df_ciro[i1:i], tfidf_ciro).toarray())
    else:
        predict_ciro_tfidf_rf = np.append(predict_ciro_tfidf_rf, RandomForest_ciro_tfidf.predict(tfidf_teste(df_ciro[i1:i], tfidf_ciro).toarray()))
    i1=i

predict_ciro_tfidf_rf = np.append(predict_ciro_tfidf_rf,RandomForest_ciro_tfidf.predict(tfidf_teste(df_ciro[i1:], tfidf_ciro).toarray()))

df_ciro['predict_tfidf_RandomForest'] = predict_ciro_tfidf_rf

np.unique(predict_ciro_tfidf_rf, return_counts=True)

(array([-1,  0,  1]), array([    13,     12, 498041], dtype=int64))

### Ciro - SVM - bw

In [54]:
svc_ciro_bw = LinearSVC()
svc_ciro_bw = svc_ciro_bw.fit(X_bw_ciro_train.toarray(), Y_ciro_train)

i1=0
for i in range(5000,len(df_ciro),5000):
    if (i==5000):
        predict_ciro_bw_svc = svc_ciro_bw.predict(Bag_of_words_teste(df_ciro[i1:i], bw_ciro).toarray())
    else:
        predict_ciro_bw_svc = np.append(predict_ciro_bw_svc, svc_ciro_bw.predict(Bag_of_words_teste(df_ciro[i1:i], bw_ciro).toarray()))
    i1=i

predict_ciro_bw_svc = np.append(predict_ciro_bw_svc,svc_ciro_bw.predict(Bag_of_words_teste(df_ciro[i1:], bw_ciro).toarray()))

df_ciro['predict_bw_svc'] = predict_ciro_bw_svc

np.unique(predict_ciro_bw_svc, return_counts=True)

(array([-1,  0,  1]), array([    90,     25, 497951], dtype=int64))

### Ciro - SVM - tfidf

In [55]:
svc_ciro_tfidf = LinearSVC()
svc_ciro_tfidf = svc_ciro_tfidf.fit(X_tfidf_ciro_train.toarray(), Y_ciro_train)

i1=0
for i in range(5000,len(df_ciro),5000):
    if (i==5000):
        predict_ciro_tfidf_svc = svc_ciro_tfidf.predict(tfidf_teste(df_ciro[i1:i], tfidf_ciro).toarray())
    else:
        predict_ciro_tfidf_svc = np.append(predict_ciro_tfidf_svc, svc_ciro_tfidf.predict(tfidf_teste(df_ciro[i1:i], tfidf_ciro).toarray()))
    i1=i

predict_ciro_tfidf_svc = np.append(predict_ciro_tfidf_svc,svc_ciro_tfidf.predict(tfidf_teste(df_ciro[i1:], tfidf_ciro).toarray()))

df_ciro['predict_tfidf_svc'] = predict_ciro_tfidf_svc

np.unique(predict_ciro_tfidf_svc, return_counts=True)

(array([-1,  0,  1]), array([    14,     10, 498042], dtype=int64))

### Ciro - MLP - bw

In [63]:
mlp_ciro_bw = MLPClassifier()
mlp_ciro_bw = mlp_ciro_bw.fit(X_bw_ciro_train.toarray(), Y_ciro_train)

i1=0
for i in range(5000,len(df_ciro),5000):
    if (i==5000):
        predict_ciro_bw_mlp = mlp_ciro_bw.predict(Bag_of_words_teste(df_ciro[i1:i], bw_ciro).toarray())
    else:
        predict_ciro_bw_mlp = np.append(predict_ciro_bw_mlp, mlp_ciro_bw.predict(Bag_of_words_teste(df_ciro[i1:i], bw_ciro).toarray()))
    i1=i

predict_ciro_bw_mlp = np.append(predict_ciro_bw_mlp,mlp_ciro_bw.predict(Bag_of_words_teste(df_ciro[i1:], bw_ciro).toarray()))

df_ciro['predict_bw_mlp'] = predict_ciro_bw_mlp
df_ciro['predict_bw_mlp2'] = predict_ciro_bw_mlp

np.unique(predict_ciro_bw_mlp, return_counts=True)

(array([-1,  0,  1]), array([    22,     17, 498027], dtype=int64))

### Ciro - MLP - tfidf

In [66]:
mlp_ciro_tfidf = MLPClassifier()
mlp_ciro_tfidf = mlp_ciro_tfidf.fit(X_tfidf_ciro_train.toarray(), Y_ciro_train)

i1=0
for i in range(5000,len(df_ciro),5000):
    if (i==5000):
        predict_ciro_tfidf_mlp = mlp_ciro_tfidf.predict(tfidf_teste(df_ciro[i1:i], tfidf_ciro).toarray())
    else:
        predict_ciro_tfidf_mlp = np.append(predict_ciro_tfidf_mlp, mlp_ciro_tfidf.predict(tfidf_teste(df_ciro[i1:i], tfidf_ciro).toarray()))
    i1=i

predict_ciro_tfidf_mlp = np.append(predict_ciro_tfidf_mlp,mlp_ciro_tfidf.predict(tfidf_teste(df_ciro[i1:], tfidf_ciro).toarray()))

df_ciro['predict_tfidf_mlp'] = predict_ciro_tfidf_mlp
df_ciro['predict_tfidf_mlp2'] = predict_ciro_tfidf_mlp

np.unique(predict_ciro_tfidf_mlp, return_counts=True)

(array([-1,  0,  1]), array([    30,     14, 498022], dtype=int64))

In [67]:
df_bolsonaro.to_excel('bolsonaro_predict.xlsx')
df_lula.to_excel('lula_predict.xlsx')
df_simone.to_excel('simone_predict.xlsx')
df_ciro.to_excel('ciro_predict.xlsx')

In [93]:
def VotacaoPredict(df):
    for i in df.index:
        pos=0
        neu=0
        neg=0
        for j in ['predict_tfidf_mlp','predict_bw_mlp',
                  'predict_tfidf_svc','predict_bw_svc',
                 'predict_tfidf_RandomForest','predict_bw_RandomForest',
                 'predict_tfidf_NaiveBayes','predict_bw_NaiveBayes',
                 'predict_tfidf_ArvoreDeDecisao','predict_bw_ArvoreDeDecisao']:
            if (df.loc[i,j]==1):
                pos+=1
            elif (df.loc[i,j]==0):
                neu+=1    
            else:
                neg+=1
            
        if(neu>2):
            df.loc[i,'VotacaoPredict_ajust'] = 0
        elif(neg>2):
            df.loc[i,'VotacaoPredict_ajust'] = -1
        else:
            df.loc[i,'VotacaoPredict_ajust'] = 1
        
        if((neu>=neg)& (neu>=pos)):
            df.loc[i,'VotacaoPredict_norm'] = 0
        elif((neg>=pos)& (neg>=neu)):
            df.loc[i,'VotacaoPredict_norm'] = -1
        else:
            df.loc[i,'VotacaoPredict_norm'] = 1     
    print(df['VotacaoPredict_ajust'].value_counts())
    print(df['VotacaoPredict_norm'].value_counts())        
    return df

In [123]:

for c in df_ciro_predict2.columns:
    print ("---- %s ---" % c)
    print (df_ciro_predict2[c].value_counts())

---- Data_post ---
2022-10-02T16:59:00Z    100
2022-10-01T00:39:00Z    100
2022-09-30T10:18:00Z    100
2022-09-30T10:21:00Z    100
2022-09-30T10:22:00Z    100
                       ... 
2022-08-21T01:44:00Z      1
2022-08-16T23:47:00Z      1
2022-08-21T22:41:00Z      1
2022-08-19T11:04:00Z      1
2022-08-20T08:50:00Z      1
Name: Data_post, Length: 14274, dtype: int64
---- ID ---
1.575801e+18    2
1.576026e+18    2
1.575661e+18    2
1.575630e+18    2
1.575832e+18    2
               ..
1.576049e+18    1
1.576049e+18    1
1.576049e+18    1
1.576049e+18    1
1.561503e+18    1
Name: ID, Length: 498029, dtype: int64
---- Texto ---
RT @oRodCecim: Paris: a\n\nCiro Gomes: https://t.co/L2Bco470d5                                                                                                                                                                                                                                             4783
RT @runmand: nem a cidade natal de ciro apoiando ele        

 1.0    497961
 0.0        57
-1.0        48
Name: VotacaoPredict_ajust, dtype: int64
---- VotacaoPredict_norm ---
 1.0    498035
-1.0        18
 0.0        13
Name: VotacaoPredict_norm, dtype: int64


In [94]:
df_bolsonaro_predict2 = VotacaoPredict(df_bolsonaro)
df_lula_predict2 = VotacaoPredict(df_lula)
df_simone_predict2 = VotacaoPredict(df_simone)
df_ciro_predict2 = VotacaoPredict(df_ciro)

 1.0    715776
-1.0    226020
 0.0      4642
Name: VotacaoPredict_ajust, dtype: int64
 1.0    850903
-1.0     92718
 0.0      2817
Name: VotacaoPredict_norm, dtype: int64
 1.0    744842
-1.0    186772
 0.0       116
Name: VotacaoPredict_ajust, dtype: int64
 1.0    856444
-1.0     75247
 0.0        39
Name: VotacaoPredict_norm, dtype: int64
 0.0    90119
 1.0    34843
-1.0     6200
Name: VotacaoPredict_ajust, dtype: int64
 0.0    68633
 1.0    57739
-1.0     4790
Name: VotacaoPredict_norm, dtype: int64
 1.0    497961
 0.0        57
-1.0        48
Name: VotacaoPredict_ajust, dtype: int64
 1.0    498035
-1.0        18
 0.0        13
Name: VotacaoPredict_norm, dtype: int64


In [83]:
df_bolsonaro_predict2 = VotacaoPredict(df_bolsonaro)
df_lula_predict2 = VotacaoPredict(df_lula)
df_simone_predict2 = VotacaoPredict(df_simone)
df_ciro_predict2 = VotacaoPredict(df_ciro)

 1.0    496314
-1.0    429653
 0.0     20471
Name: VotacaoPredict_ajust, dtype: int64
-1.0    478582
 1.0    445607
 0.0      7541
Name: VotacaoPredict_ajust, dtype: int64
 0.0    99096
 1.0    25411
-1.0     6655
Name: VotacaoPredict_ajust, dtype: int64
 1.0    489348
-1.0      5379
 0.0      3339
Name: VotacaoPredict_ajust, dtype: int64


In [115]:
print(df_bolsonaro_predict2['VotacaoPredict_ajust'].value_counts())
print(df_lula_predict2['VotacaoPredict_norm'].value_counts())
print(df_simone_predict2['VotacaoPredict_norm'].value_counts())
print(df_ciro_predict2['VotacaoPredict_norm'].value_counts())

 1.0    715776
-1.0    226020
 0.0      4642
Name: VotacaoPredict_ajust, dtype: int64
 1.0    856444
-1.0     75247
 0.0        39
Name: VotacaoPredict_norm, dtype: int64
 0.0    68633
 1.0    57739
-1.0     4790
Name: VotacaoPredict_norm, dtype: int64
 1.0    498035
-1.0        18
 0.0        13
Name: VotacaoPredict_norm, dtype: int64


## df_lula_predict2.loc[931705,'VotacaoPredict_norm']

In [101]:
df_lula_train['Sentimento'].value_counts()

p    10322
n     1758
x       25
Name: Sentimento, dtype: int64

In [103]:
df_lula_predict2['VotacaoPredict_ajust'].value_counts()

 1.0    744842
-1.0    186772
 0.0       116
Name: VotacaoPredict_ajust, dtype: int64

In [104]:
df_lula_predict2[df_lula_predict2['VotacaoPredict_ajust']==-1]['Texto']

18        RT @futurehadid: lula assistindo a dua lipa pe...
23        @RicardoBrisa55 @flferronato @TSEjusbr https:/...
48        RT @kimluvthv: lula assistindo taehyung cantar...
71        RT @JoaquinTeixeira: URNAS FECHADAS EM CUBA 🇨🇺...
81                  lula vencendo em todos os países veeeei
                                ...                        
931703    Em entrevista ao podcast Podpah, Lula erra ao ...
931704    RT @LeonMenez: Esse aqui é pra você compartilh...
931705    @roxmo O Lula deveria está inelegível pelo mal...
931716    RT @BrazilFight: EDUARDO BOLSONARO CONVIDA LUL...
931725    RT @ClaudiaBahia_13: Se tem um homem no brasil...
Name: Texto, Length: 186772, dtype: object

In [96]:
df_lula_predict2[['Texto', 'VotacaoPredict_ajust','VotacaoPredict_norm']]

Texto  \
0       RT @Carlinhosmaiaof: Indo votar 13 indo votar ...   
1        RT @lelispatricia: LULA PRESIDENTE HOJE!!!! ⭐️❤️   
2       espero que o lula tenha sentido a dedada forte...   
3       RT @purpleumbrelIa: gente eu to tao ansiosa p ...   
4                   RT @BlogdoNoblat: Lula se elege hoje?   
...                                                   ...   
931725  RT @ClaudiaBahia_13: Se tem um homem no brasil...   
931726  RT @IvanValente: Lula e Bolsonaro estarão posi...   
931727               Lula sempre! https://t.co/wGjjcnKh6E   
931728  RT @ricardope: @OGloboPolitica A campanha do L...   
931729  RT @kimpaim: Lula quer que a população "enfren...   

        VotacaoPredict_ajust  VotacaoPredict_norm  
0                        1.0                  1.0  
1                        1.0                  1.0  
2                        1.0                  1.0  
3                        1.0                  1.0  
4                        1.0                  1.0  
...                      ...                  ...  
931725                  -1.0                  1.0  
931726                   1.0                  1.0  
931727                   1.0                  1.0  
931728                   1.0                  1.0  
931729                   1.0                  1.0  

[931730 rows x 3 columns]

In [87]:
df_lula_predict[['Texto', 'VotacaoPredict_ajust','VotacaoPredict_norm']]

Texto  \
0       RT @Carlinhosmaiaof: Indo votar 13 indo votar ...   
1        RT @lelispatricia: LULA PRESIDENTE HOJE!!!! ⭐️❤️   
2       espero que o lula tenha sentido a dedada forte...   
3       RT @purpleumbrelIa: gente eu to tao ansiosa p ...   
4                   RT @BlogdoNoblat: Lula se elege hoje?   
...                                                   ...   
931725  RT @ClaudiaBahia_13: Se tem um homem no brasil...   
931726  RT @IvanValente: Lula e Bolsonaro estarão posi...   
931727               Lula sempre! https://t.co/wGjjcnKh6E   
931728  RT @ricardope: @OGloboPolitica A campanha do L...   
931729  RT @kimpaim: Lula quer que a população "enfren...   

        VotacaoPredict_ajust  VotacaoPredict_norm  
0                       -1.0                  1.0  
1                       -1.0                  1.0  
2                        1.0                  1.0  
3                        1.0                  1.0  
4                       -1.0                  1.0  
...                      ...                  ...  
931725                  -1.0                  1.0  
931726                  -1.0                  1.0  
931727                   0.0                  1.0  
931728                  -1.0                  1.0  
931729                   1.0                  1.0  

[931730 rows x 3 columns]

In [95]:
df_bolsonaro_predict2.to_excel('bolsonaro_resultado2.xlsx')
df_lula_predict2.to_excel('lula_resultado2.xlsx')
df_simone_predict2.to_excel('simone_resultado2.xlsx')
df_ciro_predict2.to_excel('ciro_resultado2.xlsx')

In [85]:
df_bolsonaro_predict

Data_post            ID  \
0       2022-10-02T16:59:00Z  1.576618e+18   
1       2022-10-02T16:59:00Z  1.576618e+18   
2       2022-10-02T16:59:00Z  1.576618e+18   
3       2022-10-02T16:59:00Z  1.576618e+18   
4       2022-10-02T16:59:00Z  1.576618e+18   
...                      ...           ...   
946433  2022-08-21T23:59:00Z  1.561503e+18   
946434  2022-08-21T23:59:00Z  1.561503e+18   
946435  2022-08-21T23:59:00Z  1.561503e+18   
946436  2022-08-21T23:59:00Z  1.561503e+18   
946437  2022-08-21T23:59:00Z  1.561503e+18   

                                                    Texto Eh_RT  \
0       RT @lucasrohan: BOLSONARO PERDENDO DE LAVADA E...     S   
1       @ArturSalvador5 @FusionFPX @DaviPer38812310 @j...     N   
2       RT @JenoOliveiraa: No Japão Bolsonaro tem vitó...     S   
3       RT @reinaldoazevedo: Eleitor pilantra de Bolso...     S   
4       RT @AugustoNPistola: Com a liderança do Bolson...     S   
...                                                   ...   ...   
946433  RT @IvanValente: Lula e Bolsonaro estarão posi...     S   
946434  @JoelPinheiro85 No fundo você está querendo de...     N   
946435  RT @TradutordoBR: Você também vai assistir a e...     S   
946436  RT @genriquez191: *Bolsonaro alfineta Macron a...     S   
946437  RT @fellipebambam: Nosso Presidente Bolsonaro ...     S   

                                               novo_texto  \
0       ['lucasrohan', 'bolsonar', 'perd', 'lav', 'bra...   
1       ['artursalv', 'fusionfpx', 'davip', 'josim', '...   
2       ['jenoliveira', 'jap', 'bolsonar', 'vitor', 'e...   
3       ['reinaldoazeved', 'elei', 'pilantr', 'bolsona...   
4       ['augustonpistol', 'lideranc', 'bolsonar', 'pe...   
...                                                   ...   
946433  ['ivanval', 'lul', 'bolsonar', 'est', 'posicio...   
946434  ['joelpinh', 'fund', 'quer', 'diz', 'bolsonar'...   
946435  ['tradutordobr', 'vai', 'asist', 'entrev', 'bo...   
946436  ['genriqu', 'bolsonar', 'alfinet', 'macron', '...   
946437  ['felipebamb', 'presid', 'bolsonar', 'michel',...   

        predict_bw_ArvoreDeDecisao  predict_tfidf_ArvoreDeDecisao  \
0                               -1                              1   
1                               -1                             -1   
2                               -1                              1   
3                                1                              1   
4                                1                              1   
...                            ...                            ...   
946433                           1                              1   
946434                           1                              1   
946435                           1                              1   
946436                           1                              1   
946437                          -1                              1   

        predict_bw_NaiveBayes  predict_tfidf_NaiveBayes  \
0                          -1                        -1   
1                          -1                        -1   
2                           1                         1   
3                           1                         1   
4                           1                         1   
...                       ...                       ...   
946433                      1                         1   
946434                      1                         1   
946435                      1                         1   
946436                     -1                        -1   
946437                      1                         1   

        predict_bw_RandomForest  predict_tfidf_RandomForest  predict_bw_svc  \
0                             1                           1               1   
1                            -1                          -1              -1   
2                             1                           1              -1   
3                             1                           1              -

In [80]:
df_bolsonaro_predict['VotacaoPredict_ajust'].value_counts()

 1.0    507782
-1.0    438656
Name: VotacaoPredict_ajust, dtype: int64

In [27]:
# df_bolsonaro = pd.read_excel('bolsonaro_predict1.xlsx', index_col=0)
# df_lula = pd.read_excel('lula_predict1.xlsx', index_col=0)
# df_simone = pd.read_excel('simone_predict1.xlsx', index_col=0)
# df_ciro = pd.read_excel('ciro_predict1.xlsx', index_col=0)

Data_post            ID  \
0       2022-10-02T16:59:00Z  1.576618e+18   
1       2022-10-02T16:59:00Z  1.576618e+18   
2       2022-10-02T16:59:00Z  1.576618e+18   
3       2022-10-02T16:59:00Z  1.576618e+18   
4       2022-10-02T16:59:00Z  1.576618e+18   
...                      ...           ...   
946433  2022-08-21T23:59:00Z  1.561503e+18   
946434  2022-08-21T23:59:00Z  1.561503e+18   
946435  2022-08-21T23:59:00Z  1.561503e+18   
946436  2022-08-21T23:59:00Z  1.561503e+18   
946437  2022-08-21T23:59:00Z  1.561503e+18   

                                                    Texto Eh_RT  \
0       RT @lucasrohan: BOLSONARO PERDENDO DE LAVADA E...     S   
1       @ArturSalvador5 @FusionFPX @DaviPer38812310 @j...     N   
2       RT @JenoOliveiraa: No Japão Bolsonaro tem vitó...     S   
3       RT @reinaldoazevedo: Eleitor pilantra de Bolso...     S   
4       RT @AugustoNPistola: Com a liderança do Bolson...     S   
...                                                   ...   ...   
946433  RT @IvanValente: Lula e Bolsonaro estarão posi...     S   
946434  @JoelPinheiro85 No fundo você está querendo de...     N   
946435  RT @TradutordoBR: Você também vai assistir a e...     S   
946436  RT @genriquez191: *Bolsonaro alfineta Macron a...     S   
946437  RT @fellipebambam: Nosso Presidente Bolsonaro ...     S   

                                               novo_texto  \
0       ['lucasrohan', 'bolsonar', 'perd', 'lav', 'bra...   
1       ['artursalv', 'fusionfpx', 'davip', 'josim', '...   
2       ['jenoliveira', 'jap', 'bolsonar', 'vitor', 'e...   
3       ['reinaldoazeved', 'elei', 'pilantr', 'bolsona...   
4       ['augustonpistol', 'lideranc', 'bolsonar', 'pe...   
...                                                   ...   
946433  ['ivanval', 'lul', 'bolsonar', 'est', 'posicio...   
946434  ['joelpinh', 'fund', 'quer', 'diz', 'bolsonar'...   
946435  ['tradutordobr', 'vai', 'asist', 'entrev', 'bo...   
946436  ['genriqu', 'bolsonar', 'alfinet', 'macron', '...   
946437  ['felipebamb', 'presid', 'bolsonar', 'michel',...   

        predict_bw_ArvoreDeDecisao  predict_tfidf_ArvoreDeDecisao  \
0                               -1                              1   
1                               -1                             -1   
2                               -1                              1   
3                                1                              1   
4                                1                              1   
...                            ...                            ...   
946433                           1                              1   
946434                           1                              1   
946435                           1                              1   
946436                           1                              1   
946437                          -1                              1   

        predict_bw_NaiveBayes  predict_tfidf_NaiveBayes  
0                          -1                        -1  
1                          -1                        -1  
2                           1                         1  
3                           1                         1  
4                           1                         1  
...                       ...                       ...  
946433                      1                         1  
946434                      1                         1  
946435                      1                         1  
946436                     -1                        -1  
946437                      1                         1  

[946438 rows x 9 columns]